### ISSUE TITLE
Running the tool?

### ISSUE THREAD

**Issue by brian428** [dbrant/QICStreamReader#1]
Could you update the readme with some instructions on using this tool? It looks like it's a Visual Studio project, but beyond that I'm not sure how to actually use this to read a tape. Any info or tips on how to use it would be great. Thanks.

**Comment by dbrant** [comment]
Sure, I'll try to get around to fleshing out the readme a bit further.  But basically it is a Visual Studio project that you can open and build yourself.

However, just to clarify: this is not actually used to read tapes themselves, but instead it's for decoding tape images.  In other words, it expects you to have a binary dump of the tape beforehand, and will decode the contents of the dump, assuming it was saved using the QICStream format.
