### ISSUE TITLE
binary request

### ISSUE THREAD

**Issue by gi1mic** [dbrant/QICStreamReader#2]
Any possibility you could add the pre-compiled binaries to this project? 

I tried building them but I can't get them to work on Win98se due to version issues or is your process to simply grab binary copies of the tapes using Linux and then process the recovered files on another machine?

I have a bunch of QIC-80 tapes and a drive but I don't remember which backup programs I used to create them. I have at some point used win95 backup, NT Backup, Arcserve, arcadabackup, conorbackup and a driver that made the tape drive look like a floppy disc so a few possibilities!

I am just curious to see what is on the tapes and this exercise has become a time sink - getting win98se running again was a pain. I had only kept one old motherboard with a floppy interface and then I made the mistake of trying to use 1GB of memory which caused lots of issues.

I have setup Ubuntu on the same box with zftape  but it is still a work in progress to the necessary software installed as most of what I want to use will not run on old machines anymore. Even sharing drives with samba is a pain to get working :-)

If I ever get sorted I will then try looking at me  small collection of SCSI DAT drives and tapes!

**Comment by dbrant** [comment]
These tools are _only_ for post-processing binary images of tapes that you've already acquired using Linux. They are not intended to run on older versions of Windows, and don't actually read live data from tape drives.

If you're working towards running Linux with `ftape`, I would encourage that path.

**Comment by gi1mic** [comment]
OK, thanks for the quick reply!

**Comment by gi1mic** [comment]
And also for the hardwork!
